#!/usr/bin/env node
// Internal helper for rules_nextjs's `next_build` action.
//
// Writes a thin `next.config.mjs` wrapper at `dstConfig` that imports
// the user's original `next.config.*` (`srcConfig`) and composes a
// webpack hook adding `resolve.extensionAlias` so `.js` imports can
// fall through to `.jsx`/`.ts`/`.tsx`.
//
// Why: the workspace's shared tsconfig sets `"jsx": "preserve"` so
// ts_project emits `.jsx` (not `.js`) for `.tsx` sources. Compiled
// `.ts` modules in the npm_package still import siblings with `.js`
// (tsc doesn't rewrite specifiers). Webpack doesn't auto-fall-back
// from `.js` to `.jsx`, so those imports fail. extensionAlias
// teaches webpack the mapping. This is harmless for `.js` files
// that *do* exist — webpack tries each candidate in order.
//
// Usage: node write_next_config_wrapper.mjs <srcConfig> <dstConfig>

import fs from 'node:fs';
import path from 'node:path';

const [, , src, dst] = process.argv;
if (!src || !dst) {
  console.error('usage: write_next_config_wrapper.mjs <srcConfig> <dstConfig>');
  process.exit(1);
}

const absSrc = path.isAbsolute(src) ? src : path.resolve(path.dirname(dst), src);
const srcLit = JSON.stringify(absSrc);

const wrapper = `// Generated by rules_nextjs. Wraps the user's next.config to add
// resolve.extensionAlias so .js imports fall back to .jsx/.ts/.tsx.
// See defs.bzl + private/write_next_config_wrapper.mjs for context.
import userConfigModule from ${srcLit};
const resolved = typeof userConfigModule === 'function'
    ? await userConfigModule({ defaultConfig: {} })
    : userConfigModule;
const cfg = { ...resolved };
const userWebpack = cfg.webpack;
cfg.webpack = (config, ctx) => {
    if (userWebpack) config = userWebpack(config, ctx);
    config.resolve = config.resolve || {};
    config.resolve.extensionAlias = {
        ...(config.resolve.extensionAlias || {}),
        '.js': ['.js', '.jsx', '.ts', '.tsx'],
        '.mjs': ['.mjs', '.mts'],
    };
    return config;
};
export default cfg;
`;

fs.writeFileSync(dst, wrapper);
